AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for bigfoot-services Orders service

Globals:
  Function:
    Timeout: 20
    Tracing: Active
    Runtime: Python_3_12
    Handler: app.handler
    MemorySize: 128
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref OrdersTable
Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Users
      AttributeDefinitions:
        - AttributeName: userid
          AttributeType: S
      KeySchema:
        - AttributeName: userid
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  OrdersTable:
    Description: DynamoDB Orders table
    Value: !Ref OrdersTable
